/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.vote.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.vote.model.VoteEntry;
import com.liferay.vote.model.VoteEntryModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VoteEntry service. Represents a row in the &quot;VoteEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.vote.model.VoteEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VoteEntryImpl}.
 * </p>
 *
 * @author Howie Chou
 * @see VoteEntryImpl
 * @see com.liferay.vote.model.VoteEntry
 * @see com.liferay.vote.model.VoteEntryModel
 * @generated
 */
public class VoteEntryModelImpl extends BaseModelImpl<VoteEntry>
	implements VoteEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vote entry model instance should use the {@link com.liferay.vote.model.VoteEntry} interface instead.
	 */
	public static final String TABLE_NAME = "VoteEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "voteEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "voteBallotId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table VoteEntry (voteEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,voteBallotId LONG)";
	public static final String TABLE_SQL_DROP = "drop table VoteEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY voteEntry.voteEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VoteEntry.voteEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.vote.model.VoteEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.vote.model.VoteEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.vote.model.VoteEntry"));

	public VoteEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _voteEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVoteEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _voteEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VoteEntry.class;
	}

	@Override
	public String getModelClassName() {
		return VoteEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("voteEntryId", getVoteEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("voteBallotId", getVoteBallotId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long voteEntryId = (Long)attributes.get("voteEntryId");

		if (voteEntryId != null) {
			setVoteEntryId(voteEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long voteBallotId = (Long)attributes.get("voteBallotId");

		if (voteBallotId != null) {
			setVoteBallotId(voteBallotId);
		}
	}

	@Override
	public long getVoteEntryId() {
		return _voteEntryId;
	}

	@Override
	public void setVoteEntryId(long voteEntryId) {
		_voteEntryId = voteEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getVoteBallotId() {
		return _voteBallotId;
	}

	@Override
	public void setVoteBallotId(long voteBallotId) {
		_voteBallotId = voteBallotId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			VoteEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VoteEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VoteEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VoteEntryImpl voteEntryImpl = new VoteEntryImpl();

		voteEntryImpl.setVoteEntryId(getVoteEntryId());
		voteEntryImpl.setCompanyId(getCompanyId());
		voteEntryImpl.setUserId(getUserId());
		voteEntryImpl.setUserName(getUserName());
		voteEntryImpl.setCreateDate(getCreateDate());
		voteEntryImpl.setModifiedDate(getModifiedDate());
		voteEntryImpl.setVoteBallotId(getVoteBallotId());

		voteEntryImpl.resetOriginalValues();

		return voteEntryImpl;
	}

	@Override
	public int compareTo(VoteEntry voteEntry) {
		long primaryKey = voteEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VoteEntry)) {
			return false;
		}

		VoteEntry voteEntry = (VoteEntry)obj;

		long primaryKey = voteEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VoteEntry> toCacheModel() {
		VoteEntryCacheModel voteEntryCacheModel = new VoteEntryCacheModel();

		voteEntryCacheModel.voteEntryId = getVoteEntryId();

		voteEntryCacheModel.companyId = getCompanyId();

		voteEntryCacheModel.userId = getUserId();

		voteEntryCacheModel.userName = getUserName();

		String userName = voteEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			voteEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			voteEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			voteEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			voteEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			voteEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		voteEntryCacheModel.voteBallotId = getVoteBallotId();

		return voteEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{voteEntryId=");
		sb.append(getVoteEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", voteBallotId=");
		sb.append(getVoteBallotId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.liferay.vote.model.VoteEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>voteEntryId</column-name><column-value><![CDATA[");
		sb.append(getVoteEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>voteBallotId</column-name><column-value><![CDATA[");
		sb.append(getVoteBallotId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VoteEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VoteEntry.class
		};
	private long _voteEntryId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _voteBallotId;
	private VoteEntry _escapedModel;
}