/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.vote.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VoteEntry service. Represents a row in the &quot;VoteEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.vote.model.impl.VoteEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.vote.model.impl.VoteEntryImpl}.
 * </p>
 *
 * @author Howie Chou
 * @see VoteEntry
 * @see com.liferay.vote.model.impl.VoteEntryImpl
 * @see com.liferay.vote.model.impl.VoteEntryModelImpl
 * @generated
 */
public interface VoteEntryModel extends AuditedModel, BaseModel<VoteEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vote entry model instance should use the {@link VoteEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this vote entry.
	 *
	 * @return the primary key of this vote entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vote entry.
	 *
	 * @param primaryKey the primary key of this vote entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vote entry ID of this vote entry.
	 *
	 * @return the vote entry ID of this vote entry
	 */
	public long getVoteEntryId();

	/**
	 * Sets the vote entry ID of this vote entry.
	 *
	 * @param voteEntryId the vote entry ID of this vote entry
	 */
	public void setVoteEntryId(long voteEntryId);

	/**
	 * Returns the company ID of this vote entry.
	 *
	 * @return the company ID of this vote entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vote entry.
	 *
	 * @param companyId the company ID of this vote entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vote entry.
	 *
	 * @return the user ID of this vote entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vote entry.
	 *
	 * @param userId the user ID of this vote entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vote entry.
	 *
	 * @return the user uuid of this vote entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vote entry.
	 *
	 * @param userUuid the user uuid of this vote entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vote entry.
	 *
	 * @return the user name of this vote entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vote entry.
	 *
	 * @param userName the user name of this vote entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vote entry.
	 *
	 * @return the create date of this vote entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vote entry.
	 *
	 * @param createDate the create date of this vote entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vote entry.
	 *
	 * @return the modified date of this vote entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vote entry.
	 *
	 * @param modifiedDate the modified date of this vote entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the vote ballot ID of this vote entry.
	 *
	 * @return the vote ballot ID of this vote entry
	 */
	public long getVoteBallotId();

	/**
	 * Sets the vote ballot ID of this vote entry.
	 *
	 * @param voteBallotId the vote ballot ID of this vote entry
	 */
	public void setVoteBallotId(long voteBallotId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.vote.model.VoteEntry voteEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.vote.model.VoteEntry> toCacheModel();

	@Override
	public com.liferay.vote.model.VoteEntry toEscapedModel();

	@Override
	public com.liferay.vote.model.VoteEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}