/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.vote.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VoteBallot service. Represents a row in the &quot;VoteBallot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.vote.model.impl.VoteBallotModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.vote.model.impl.VoteBallotImpl}.
 * </p>
 *
 * @author Howie Chou
 * @see VoteBallot
 * @see com.liferay.vote.model.impl.VoteBallotImpl
 * @see com.liferay.vote.model.impl.VoteBallotModelImpl
 * @generated
 */
public interface VoteBallotModel extends AuditedModel, BaseModel<VoteBallot> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vote ballot model instance should use the {@link VoteBallot} interface instead.
	 */

	/**
	 * Returns the primary key of this vote ballot.
	 *
	 * @return the primary key of this vote ballot
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vote ballot.
	 *
	 * @param primaryKey the primary key of this vote ballot
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vote ballot ID of this vote ballot.
	 *
	 * @return the vote ballot ID of this vote ballot
	 */
	public long getVoteBallotId();

	/**
	 * Sets the vote ballot ID of this vote ballot.
	 *
	 * @param voteBallotId the vote ballot ID of this vote ballot
	 */
	public void setVoteBallotId(long voteBallotId);

	/**
	 * Returns the company ID of this vote ballot.
	 *
	 * @return the company ID of this vote ballot
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vote ballot.
	 *
	 * @param companyId the company ID of this vote ballot
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vote ballot.
	 *
	 * @return the user ID of this vote ballot
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vote ballot.
	 *
	 * @param userId the user ID of this vote ballot
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vote ballot.
	 *
	 * @return the user uuid of this vote ballot
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vote ballot.
	 *
	 * @param userUuid the user uuid of this vote ballot
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vote ballot.
	 *
	 * @return the user name of this vote ballot
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vote ballot.
	 *
	 * @param userName the user name of this vote ballot
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vote ballot.
	 *
	 * @return the create date of this vote ballot
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vote ballot.
	 *
	 * @param createDate the create date of this vote ballot
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vote ballot.
	 *
	 * @return the modified date of this vote ballot
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vote ballot.
	 *
	 * @param modifiedDate the modified date of this vote ballot
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the vote idea type ID of this vote ballot.
	 *
	 * @return the vote idea type ID of this vote ballot
	 */
	public long getVoteIdeaTypeId();

	/**
	 * Sets the vote idea type ID of this vote ballot.
	 *
	 * @param voteIdeaTypeId the vote idea type ID of this vote ballot
	 */
	public void setVoteIdeaTypeId(long voteIdeaTypeId);

	/**
	 * Returns the name of this vote ballot.
	 *
	 * @return the name of this vote ballot
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vote ballot.
	 *
	 * @param name the name of this vote ballot
	 */
	public void setName(String name);

	/**
	 * Returns the description of this vote ballot.
	 *
	 * @return the description of this vote ballot
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vote ballot.
	 *
	 * @param description the description of this vote ballot
	 */
	public void setDescription(String description);

	/**
	 * Returns the end date of this vote ballot.
	 *
	 * @return the end date of this vote ballot
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this vote ballot.
	 *
	 * @param endDate the end date of this vote ballot
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.vote.model.VoteBallot voteBallot);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.vote.model.VoteBallot> toCacheModel();

	@Override
	public com.liferay.vote.model.VoteBallot toEscapedModel();

	@Override
	public com.liferay.vote.model.VoteBallot toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}